variables:
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1

  DRIVER_CONTAINER_GITLAB: registry.gitlab.com/bvobart/ceiled/ceiled-driver
  SERVER_CONTAINER_GITLAB: registry.gitlab.com/bvobart/ceiled/ceiled-server
  WEB_CONTAINER_GITLAB: registry.gitlab.com/bvobart/ceiled/ceiled-web
  
  DRIVER_CONTAINER_DOCKER: bvobart/ceiled-driver
  SERVER_CONTAINER_DOCKER: bvobart/ceiled-server
  WEB_CONTAINER_DOCKER: bvobart/ceiled-web


stages:
  - build
  - publish
  - deploy

image: docker:latest
services:
  - docker:dind

#----------------------------------------------------------
# Build
#----------------------------------------------------------
build - ceiled-driver:
  stage: build
  before_script:
    - cd ceiled-driver
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # Build container with inline cache
    - docker pull $DRIVER_CONTAINER_GITLAB:$CI_COMMIT_REF_SLUG
    - docker build 
      --target builder
      --build-arg BUILDKIT_INLINE_CACHE=1
      -t $DRIVER_CONTAINER_GITLAB
      .
    # Run tests
    - docker run $DRIVER_CONTAINER_GITLAB cargo test
    # Build production container with inline cache
    - docker build -t $DRIVER_CONTAINER_GITLAB
      --build-arg BUILDKIT_INLINE_CACHE=1
      -t $DRIVER_CONTAINER_GITLAB:$CI_COMMIT_REF_SLUG
      -t $DRIVER_CONTAINER_GITLAB:$CI_COMMIT_SHA
      -t $DRIVER_CONTAINER_GITLAB:latest
      .
    # Push container and tags to Gitlab internal registry
    - docker push $DRIVER_CONTAINER_GITLAB:$CI_COMMIT_REF_SLUG
    - docker push $DRIVER_CONTAINER_GITLAB:$CI_COMMIT_SHA
    - docker push $DRIVER_CONTAINER_GITLAB:latest

build - ceiled-server:
  stage: build
  before_script:
    - cd ceiled-server
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $SERVER_CONTAINER_GITLAB:$CI_COMMIT_REF_SLUG
    # Build container with inline cache
    - docker build 
      --target builder
      --build-arg BUILDKIT_INLINE_CACHE=1
      -t $SERVER_CONTAINER_GITLAB
      .
    # Run tests
    - docker run $SERVER_CONTAINER_GITLAB yarn test
    # Build production container with inline cache
    - docker build -t $SERVER_CONTAINER_GITLAB
      --build-arg BUILDKIT_INLINE_CACHE=1
      -t $SERVER_CONTAINER_GITLAB:$CI_COMMIT_REF_SLUG
      -t $SERVER_CONTAINER_GITLAB:$CI_COMMIT_SHA
      -t $SERVER_CONTAINER_GITLAB:latest
      .
    # Push container and tags to Gitlab internal registry
    - docker push $SERVER_CONTAINER_GITLAB:$CI_COMMIT_REF_SLUG
    - docker push $SERVER_CONTAINER_GITLAB:$CI_COMMIT_SHA
    - docker push $SERVER_CONTAINER_GITLAB:latest

build - ceiled-web:
  stage: build
  before_script:
    - cd ceiled-server
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # Build container with inline cache
    - docker pull $WEB_CONTAINER_GITLAB:$CI_COMMIT_REF_SLUG
    - docker build 
      --target builder
      --build-arg BUILDKIT_INLINE_CACHE=1
      -t $WEB_CONTAINER_GITLAB
      .
    # Run tests (no tests for ceiled-web, future)
    # - docker run $WEB_CONTAINER_GITLAB yarn test
    # Build production container with inline cache
    - docker build -t $WEB_CONTAINER_GITLAB
      --build-arg BUILDKIT_INLINE_CACHE=1
      -t $WEB_CONTAINER_GITLAB:$CI_COMMIT_REF_SLUG
      -t $WEB_CONTAINER_GITLAB:$CI_COMMIT_SHA
      -t $WEB_CONTAINER_GITLAB:latest
      .
    # Push container and tags to Gitlab internal registry
    - docker push $WEB_CONTAINER_GITLAB:$CI_COMMIT_REF_SLUG
    - docker push $WEB_CONTAINER_GITLAB:$CI_COMMIT_SHA
    - docker push $WEB_CONTAINER_GITLAB:latest

#----------------------------------------------------------
# Publish
#----------------------------------------------------------
publish - ceiled-driver:
  stage: publish
  needs:
    - build - ceiled-driver
  script:
    - echo "TODO - push ceiled-driver image from Gitlab Docker registry to Docker Hub"
  only:
    - master
    - develop

publish - ceiled-server:
  stage: publish
  needs:
    - build - ceiled-server
  script:
    - echo "TODO - push ceiled-driver image from Gitlab Docker registry to Docker Hub"
  only:
    - master
    - develop

publish - ceiled-web:
  stage: publish
  needs:
    - build - ceiled-web
  script:
    - echo "TODO - push ceiled-driver image from Gitlab Docker registry to Docker Hub"
  only:
    - master
    - develop


#----------------------------------------------------------
# Deploy
#----------------------------------------------------------
deploy:
  stage: deploy
  script:
    - echo "TODO - SSH to pacbot"
    - echo "TODO - run ceiled update"
  only:
    - master
    - develop
