matrix:
  include:
    - language: node_js
      node_js:
        - 10
      cache: yarn
      stages:
        - build
        - test
        - deploy
      
      jobs:
        include:
          - stage: build
            install: cd controller && yarn install
            script: yarn build

          - stage: build
            install: cd ceiled-web && yarn install
            script: yarn build
          
          - stage: test
            install: cd controller && yarn install
            script: yarn test
            services: 
              - mongodb
          
          - stage: deploy
            if: branch = master OR branch = develop
            before_install:
              - openssl aes-256-cbc -K $encrypted_8913863055d3_key -iv $encrypted_8913863055d3_iv -in .travis/travis_key.enc -out ~/.ssh/travis_key -d
              - chmod 600 ~/.ssh/travis_key
              - echo "bart.vanoort.is ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDpIvXSvLobd5l7nlTVGPcH6kjDrQZga40RkHVdh1RQH7Z4btuNhjwfZyjtCM4aeTPHWx7Qi15FJaUdvknWR1CU=" >> ~/.ssh/known_hosts
            install: cd ceiled-web && yarn install
            script: yarn build
            deploy:
              skip_cleanup: true
              provider: script
              script: cd .. && .travis/deploy.sh
              on:
                all_branches: true
                condition: $TRAVIS_BRANCH =~ ^develop|master$
    - language: rust
      rust: stable
      cache: cargo
      stages:
        - build
        - deploy
      
      jobs:
        include:
          - stage: build
            install: cd ceiled-driver
            script: cargo build --verbose

          - stage: deploy
            if: branch = master OR branch = develop
            before_install:
              - openssl aes-256-cbc -K $encrypted_8913863055d3_key -iv $encrypted_8913863055d3_iv -in .travis/travis_key.enc -out ~/.ssh/travis_key -d
              - chmod 600 ~/.ssh/travis_key
              - echo "bart.vanoort.is ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDpIvXSvLobd5l7nlTVGPcH6kjDrQZga40RkHVdh1RQH7Z4btuNhjwfZyjtCM4aeTPHWx7Qi15FJaUdvknWR1CU=" >> ~/.ssh/known_hosts
            install: cd ceiled-driver
            script: cargo build --release
            deploy:
              skip_cleanup: true
              provider: script
              script: cd .. && .travis/deploy.sh
              on:
                all_branches: true
                condition: $TRAVIS_BRANCH =~ ^develop|master$
