language: node_js
node_js:
  - 10
cache: yarn

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      install: cd controller && yarn install
      script: yarn build

    - stage: build
      install: cd ceiled-web && yarn install
      script: yarn build
      
    - stage: test
      install: cd controller && yarn install
      script: yarn test
