language: node_js
node_js:
  - 10
cache: yarn

stages:
  - build
  - test
  - deploy

jobs:
  include:
    - stage: build
      install: cd controller && yarn install
      script: yarn build

    - stage: build
      install: cd ceiled-web && yarn install
      script: yarn build

    - stage: test
      install: cd controller && yarn install
      script: yarn test
      services: 
        - mongodb
    
    - stage: deploy
      before_install:
        - openssl aes-256-cbc -K $encrypted_8913863055d3_key -iv $encrypted_8913863055d3_iv -in .travis/travis_key.enc -out ~/.ssh/travis_key -d
      install: cd ceiled-web && yarn install
      script: yarn build
      deploy:
        skip_cleanup: true
        provider: script
        script: .travis/deploy.sh
        branches:
          only:
            - ci
            - master
