stages:
  - build
  - deploy

jobs:
  include:

    # ceiled-driver: build, test
    - language: rust
      rust: stable
      cache: cargo
      name: "Build & Test - ceiled-driver"
      stage: build
      before_script: cd ceiled-driver
      script: 
        - cargo check
        - cargo test

    # ceiled-server: build, test
    - language: node_js
      node_js:
        - 10
      cache: yarn
      name: Build & Test - ceiled-server
      stage: build
      services:
        - mongodb
      before_install: cd ceiled-server
      install: yarn install
      script: 
        - yarn build
        - yarn test

    # ceiled-web, build
    - language: node_js
      node_js:
        - 10
      cache: yarn
      name: Build ceiled-web
      stage: build
      before_install: cd ceiled-web
      install: yarn install
      script: yarn build

    # deploy
    - language: node_js
      node_js:
        - 10
      cache: yarn
      name: Deploy ceiled-driver, ceiled-server and ceiled-web
      stage: deploy
      if: branch = master OR branch = develop
      before_install:
        - openssl aes-256-cbc -K $encrypted_8913863055d3_key -iv $encrypted_8913863055d3_iv -in .travis/travis_key.enc -out ~/.ssh/travis_key -d
        - chmod 600 ~/.ssh/travis_key
        - echo "bart.vanoort.is ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDpIvXSvLobd5l7nlTVGPcH6kjDrQZga40RkHVdh1RQH7Z4btuNhjwfZyjtCM4aeTPHWx7Qi15FJaUdvknWR1CU=" >> ~/.ssh/known_hosts
      install: cd ceiled-web && yarn install
      script: yarn build
      deploy:
        skip_cleanup: true
        provider: script
        script: cd .. && .travis/deploy.sh
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^develop|master$
